"""HTML and plain-text email rendering from PulseSummary."""

from typing import Any

import structlog
from jinja2 import BaseLoader, Environment

from app.core.models import PulseSummary

logger = structlog.get_logger()

EMAIL_TEMPLATE_HTML = """<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { border-bottom: 2px solid #2563eb; padding-bottom: 16px; margin-bottom: 24px; }
        .header h1 { margin: 0; font-size: 24px; color: #1e293b; }
        .header p { margin: 8px 0 0; color: #64748b; font-size: 14px; }
        .section { margin-bottom: 24px; }
        .section h2 { font-size: 18px; color: #334155; margin-bottom: 12px; }
        .theme { background: #f8fafc; border-radius: 8px; padding: 12px 16px; margin-bottom: 12px; }
        .theme-label { font-weight: 600; color: #1e293b; }
        .theme-meta { font-size: 13px; color: #64748b; margin-top: 4px; }
        .quote { font-style: italic; color: #475569; border-left: 3px solid #cbd5e1; padding-left: 12px; margin: 8px 0; }
        .cta { background: #2563eb; color: white; padding: 12px 24px; border-radius: 6px; text-decoration: none; display: inline-block; margin-top: 16px; }
        .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 12px; color: #94a3b8; }
    </style>
</head>
<body>
    <div class="header">
        <h1>[Weekly Pulse] {{ product }}</h1>
        <p>{{ window_start }} to {{ window_end }} &middot; {{ total_reviews }} reviews &middot; Avg {{ avg_rating }} stars</p>
    </div>

    <div class="section">
        <h2>Top Themes</h2>
        {% for theme in themes %}
        <div class="theme">
            <div class="theme-label">{{ theme.rank }}. {{ theme.label }}</div>
            <div>{{ theme.description }}</div>
            <div class="theme-meta">{{ theme.sentiment }} &middot; {{ theme.review_count }} reviews</div>
        </div>
        {% endfor %}
    </div>

    <div class="section">
        <h2>What Stakeholders Say</h2>
        {% for quote in quotes %}
        <div class="quote">&ldquo;{{ quote.text }}&rdquo;</div>
        {% endfor %}
    </div>

    <div class="section">
        {% if doc_link %}
        <a href="{{ doc_link }}" class="cta">Read Full Report &rarr;</a>
        {% else %}
        <p>The Google Doc could not be published for this run, but the summary below still reflects the latest review analysis.</p>
        {% endif %}
    </div>

    <div class="footer">
        <p>Generated by Pulse Agent &middot; Run ID: {{ run_id }}</p>
        <p>This is an automated weekly summary of public app store reviews.</p>
    </div>
</body>
</html>
"""

EMAIL_TEMPLATE_TEXT = """[Weekly Pulse] {{ product }}
{{ window_start }} to {{ window_end }} | {{ total_reviews }} reviews | Avg {{ avg_rating }} stars

TOP THEMES
{% for theme in themes %}
{{ theme.rank }}. {{ theme.label }}
   {{ theme.description }}
   Sentiment: {{ theme.sentiment }} | {{ theme.review_count }} reviews
{% endfor %}

QUOTES
{% for quote in quotes %}
"{{ quote.text }}"
{% endfor %}

{% if doc_link %}
Read the full report: {{ doc_link }}
{% else %}
Google Doc unavailable for this run. The summary above is still valid.
{% endif %}

---
Generated by Pulse Agent | Run ID: {{ run_id }}
"""


def _render_template(template_str: str, variables: dict[str, Any]) -> str:
    """Render a Jinja2 template string with variables."""
    env = Environment(loader=BaseLoader())
    template = env.from_string(template_str)
    return template.render(**variables)


class EmailRenderer:
    """Render pulse summaries as HTML and plain-text emails."""

    def render(
        self,
        summary: PulseSummary,
        doc_deep_link: str,
        run_id: str,
    ) -> tuple[str, str]:
        """Render HTML and plain-text emails.

        Args:
            summary: The pulse summary
            doc_deep_link: Link to the Google Doc section
            run_id: Run identifier for footer

        Returns:
            Tuple of (html_body, text_body)
        """
        variables = {
            "product": summary.product,
            "window_start": summary.window.start.isoformat(),
            "window_end": summary.window.end.isoformat(),
            "total_reviews": summary.stats.total_reviews,
            "avg_rating": summary.stats.avg_rating,
            "themes": [
                {
                    "rank": t.rank,
                    "label": t.label,
                    "description": t.description,
                    "sentiment": t.sentiment,
                    "review_count": t.review_count,
                }
                for t in summary.top_themes
            ],
            "quotes": [{"text": q.text} for q in summary.quotes[:3]],
            "doc_link": doc_deep_link,
            "run_id": run_id,
        }

        html = _render_template(EMAIL_TEMPLATE_HTML, variables)
        text = _render_template(EMAIL_TEMPLATE_TEXT, variables)

        logger.info(
            "Rendered email",
            product=summary.product,
            doc_link=doc_deep_link,
        )
        return html, text


def render_email(
    summary: PulseSummary,
    doc_deep_link: str,
    run_id: str,
) -> tuple[str, str]:
    """Convenience function to render email."""
    renderer = EmailRenderer()
    return renderer.render(summary, doc_deep_link, run_id)
